/**
 * Ghana search-intent map. These are grouped by page intent so copy and
 * metadata can use a small, relevant subset instead of stuffing every term
 * into every page. The map contains 35 clusters x 10 phrases = 350 phrases.
 */
export const GHANA_KEYWORD_CLUSTERS = {
  office: ["office supplies Ghana", "office stationery Ghana", "office supplies Accra", "office stationery Accra", "office supplies online Ghana", "office stationery supplier Ghana", "workplace supplies Ghana", "business supplies Accra", "office essentials Ghana", "office supply shop Ghana"],
  a4Paper: ["A4 paper Ghana", "A4 paper Accra", "buy A4 paper online Ghana", "A4 copier paper Ghana", "photocopy paper Ghana", "printer paper Accra", "office paper supplier Ghana", "80gsm A4 paper Ghana", "A4 paper bulk Ghana", "cheap A4 paper Accra"],
  toner: ["printer toner Ghana", "toner cartridge Accra", "buy toner online Ghana", "printer ink Ghana", "ink cartridge Accra", "laser toner Ghana", "toner supplier Ghana", "HP toner Ghana", "Canon toner Accra", "Epson ink Ghana"],
  writing: ["pens Ghana", "ballpoint pens Accra", "buy pens online Ghana", "office pens Ghana", "school pencils Ghana", "markers Ghana", "highlighters Accra", "writing supplies Ghana", "gel pens Ghana", "bulk pens Accra"],
  filing: ["files and folders Ghana", "office filing supplies Accra", "lever arch files Ghana", "ring binders Accra", "document wallets Ghana", "archive boxes Ghana", "file folders online Ghana", "filing cabinet accessories Ghana", "office organisation supplies Ghana", "bulk files Accra"],
  desk: ["desk accessories Ghana", "office desk organiser Accra", "staplers Ghana", "office scissors Accra", "sticky notes Ghana", "desk supplies online Ghana", "office tape Ghana", "rulers and calculators Ghana", "desk organiser Ghana", "bulk desk supplies Accra"],
  school: ["school supplies Ghana", "school stationery Accra", "buy school supplies online Ghana", "classroom supplies Ghana", "school procurement Ghana", "exercise books Accra", "school bags and stationery Ghana", "student stationery Ghana", "school supply shop Accra", "bulk school supplies Ghana"],
  art: ["art supplies Ghana", "arts and crafts Accra", "school art materials Ghana", "craft supplies online Ghana", "drawing materials Ghana", "painting supplies Accra", "classroom art supplies Ghana", "colouring pencils Ghana", "creative supplies Accra", "bulk art supplies Ghana"],
  books: ["books Ghana", "buy books online Ghana", "books shop Accra", "children books Ghana", "educational books Accra", "school books Ghana", "fiction books Ghana", "books and novels Accra", "book supplier Ghana", "new books online Ghana"],
  notebooks: ["notebooks Ghana", "exercise books Ghana", "buy notebooks online Accra", "hard cover notebooks Ghana", "spiral notebooks Accra", "journals Ghana", "writing pads Ghana", "office notebooks Ghana", "school notebooks Accra", "bulk notebooks Ghana"],
  equipment: ["office equipment Ghana", "office equipment supplier Accra", "calculators Ghana", "shredders Accra", "laminators Ghana", "binding machines Ghana", "office technology Ghana", "office equipment online Ghana", "small office equipment Accra", "business equipment Ghana"],
  computer: ["computer accessories Ghana", "office electronics Accra", "USB drives Ghana", "keyboard and mouse Ghana", "computer cables Accra", "laptop accessories Ghana", "office tech accessories Ghana", "webcam Ghana", "storage devices Accra", "computer supplies online Ghana"],
  meeting: ["meeting room supplies Ghana", "conference supplies Accra", "whiteboards Ghana", "flip chart paper Ghana", "presentation supplies Accra", "office notice boards Ghana", "meeting stationery Ghana", "training materials Accra", "conference stationery Ghana", "corporate meeting supplies Ghana"],
  packaging: ["packaging supplies Ghana", "mailing supplies Accra", "envelopes Ghana", "shipping boxes Accra", "bubble wrap Ghana", "parcel supplies Ghana", "business envelopes Accra", "packaging materials online Ghana", "labels and stickers Ghana", "bulk packaging Accra"],
  printing: ["printing supplies Ghana", "office printing supplies Accra", "printer accessories Ghana", "photocopy supplies Ghana", "printing paper Accra", "printer consumables Ghana", "print supplies online Ghana", "office printer supplies Ghana", "copy paper supplier Accra", "bulk printing supplies Ghana"],
  procurement: ["office procurement Ghana", "stationery procurement Ghana", "corporate stationery supplier Ghana", "bulk office procurement Accra", "procurement supplies Ghana", "institutional stationery Ghana", "business stationery quotation Ghana", "office supply RFQ Ghana", "workplace procurement Accra", "approved stationery supplier Ghana"],
  bulk: ["bulk office supplies Ghana", "wholesale stationery Ghana", "bulk stationery Accra", "wholesale office supplies Accra", "office supplies in bulk Ghana", "bulk A4 paper Ghana", "bulk printer toner Ghana", "bulk school stationery Ghana", "corporate bulk orders Ghana", "stationery wholesale supplier Ghana"],
  corporate: ["corporate stationery Ghana", "office restocking Ghana", "business office supplies Accra", "company stationery supplier Ghana", "corporate procurement Accra", "office setup supplies Ghana", "new office supplies Ghana", "SME office supplies Ghana", "recurring office supplies Ghana", "workplace supply partner Ghana"],
  schools: ["school stationery supplier Ghana", "school supplies procurement Accra", "classroom stationery Ghana", "school office supplies Ghana", "university stationery supplier Ghana", "school bulk order Accra", "supplies for Ghanaian schools", "school supply quotation Ghana", "educational procurement Ghana", "school stationery delivery Ghana"],
  ngo: ["NGO office supplies Ghana", "NGO stationery supplier Accra", "development organisation supplies Ghana", "charity office supplies Ghana", "project stationery procurement Ghana", "donor project supplies Accra", "NGO bulk stationery Ghana", "nonprofit office supplies Ghana", "humanitarian office supplies Ghana", "NGO procurement supplier Ghana"],
  government: ["government stationery supplier Ghana", "public sector office supplies Ghana", "government procurement stationery Accra", "ministries office supplies Ghana", "public institution stationery Ghana", "government bulk supplies Accra", "tender stationery supplier Ghana", "government office equipment Ghana", "public school supplies Ghana", "institutional procurement Accra"],
  hospitality: ["hotel office supplies Ghana", "restaurant stationery Ghana", "hospitality supplies Accra", "hotel guest stationery Ghana", "hospital office supplies Ghana", "front desk supplies Accra", "hospitality procurement Ghana", "hotel printing supplies Ghana", "restaurant packaging supplies Ghana", "hospital bulk stationery Accra"],
  construction: ["construction office supplies Ghana", "site office stationery Ghana", "engineering office supplies Accra", "project office supplies Ghana", "contractor stationery supplier Ghana", "construction printing supplies Accra", "site document filing Ghana", "building project stationery Ghana", "contractor bulk supplies Ghana", "project procurement Accra"],
  legal: ["law office supplies Ghana", "accounting office supplies Accra", "professional office stationery Ghana", "legal filing supplies Ghana", "invoice books Accra", "receipt books Ghana", "business forms Ghana", "professional stationery supplier Ghana", "audit office supplies Accra", "company records supplies Ghana"],
  accraDelivery: ["stationery delivery Accra", "office supplies delivery Accra", "same day stationery Accra", "office supplies near me Accra", "A4 paper delivery Accra", "toner delivery Accra", "office supply shop Accra delivery", "business supplies delivered Accra", "stationery courier Accra", "office restock delivery Accra"],
  temaDelivery: ["stationery delivery Tema", "office supplies delivery Tema", "office supply shop Tema", "A4 paper delivery Tema", "toner delivery Tema", "business supplies Tema Ghana", "stationery supplier Tema", "bulk stationery delivery Tema", "workplace supplies Tema", "office restocking Tema"],
  nationwide: ["nationwide stationery delivery Ghana", "office supplies delivery Ghana", "buy stationery online Ghana delivery", "office supplies shipped Ghana", "stationery supplier nationwide Ghana", "A4 paper delivery Ghana", "toner delivery nationwide Ghana", "school supplies delivery Ghana", "bulk supplies delivery Ghana", "online office supplies Ghana"],
  pickup: ["stationery shop pickup Accra", "office supplies pickup Ghana", "click and collect Accra stationery", "pick up A4 paper Accra", "shop pickup Asylum Down", "shop pickup Kanda Accra", "order online collect Accra", "stationery collection point Accra", "office supplies click collect Ghana", "PaperSource shop pickup"],
  value: ["affordable office supplies Ghana", "best stationery prices Ghana", "office supplies price Ghana", "A4 paper price Ghana", "toner price Accra", "cheap office stationery Ghana", "stationery deals Accra", "office supplies comparison Ghana", "value office supplies Ghana", "quality stationery affordable Ghana"],
  brands: ["stationery brands Ghana", "office brands Accra", "HP supplies Ghana", "Canon supplies Ghana", "Double A paper Ghana", "Oxford notebooks Ghana", "BIC pens Ghana", "Pilot pens Ghana", "Maped stationery Ghana", "trusted stationery brands Ghana"],
  tonerCompatibility: ["HP printer toner compatibility Ghana", "Canon toner cartridge guide Ghana", "Epson ink compatibility Ghana", "find toner for printer Ghana", "printer cartridge model Ghana", "toner replacement Accra", "compatible ink cartridge Ghana", "laser printer toner guide Ghana", "printer consumables compatibility", "buy correct toner Ghana"],
  paperSpecs: ["paper GSM explained Ghana", "A4 paper sizes Ghana", "A3 paper Ghana", "A5 paper Ghana", "cardstock Ghana", "coloured paper Accra", "copy paper GSM Ghana", "paper size guide Ghana", "printer paper thickness Ghana", "best paper for office printing Ghana"],
  ghanaModifiers: ["shop in Ghana online", "Ghana online shopping stationery", "Accra office shop", "Greater Accra stationery", "Ghana business supplies", "Ghana workplace essentials", "local stationery supplier Ghana", "Ghana office products", "Ghana school supplies shop", "Ghana stationery catalogue"],
  questions: ["where to buy office supplies in Ghana", "where to buy A4 paper in Accra", "where to buy printer toner in Ghana", "what stationery does a new office need", "how to order bulk stationery Ghana", "how much is A4 paper in Ghana", "does PaperSource deliver in Accra", "can I pick up stationery in Accra", "what paper GSM is best for printing", "how to choose printer toner Ghana"],
  trustAndService: ["PaperSource Ghana reviews", "reliable stationery supplier Accra", "trusted office supplies Ghana", "office supplies customer service Ghana", "stationery returns Ghana", "office supply delivery tracking Ghana", "VAT inclusive stationery Ghana", "secure stationery checkout Ghana", "business account stationery Ghana", "shop stationery with Paystack Ghana"],
  envelopes: ["envelope packs Ghana", "office envelopes Accra", "buy envelopes online Ghana", "manila envelopes Ghana", "company envelopes Accra", "A4 envelopes Ghana", "DL envelopes Ghana", "envelope supplier Accra", "envelope delivery Ghana", "bulk envelopes Ghana"],
  receipts: ["receipt pads Ghana", "receipt book Accra", "buy receipt books online Ghana", "duplicate receipt books Ghana", "cash receipt book Accra", "receipt stationery Ghana", "receipt book supplier Ghana", "company receipt books Accra", "receipt book delivery Ghana", "bulk receipt books Ghana"],
  invoices: ["invoice books Ghana", "invoice book Accra", "buy invoice books online Ghana", "carbon invoice books Ghana", "business invoice stationery Ghana", "invoice book supplier Accra", "duplicate invoice book Ghana", "sales invoice books Ghana", "invoice book delivery Accra", "bulk invoice books Ghana"],
  diaries: ["diaries Ghana", "office diaries Accra", "buy diary online Ghana", "2027 diaries Ghana", "business diaries Accra", "executive diary Ghana", "pocket diary Ghana", "diary supplier Accra", "diary delivery Ghana", "bulk diaries Ghana"],
  planners: ["planners Ghana", "weekly planner Accra", "buy planner online Ghana", "2027 planner Ghana", "office planner Ghana", "daily planner Accra", "academic planner Ghana", "planner supplier Ghana", "planner delivery Accra", "bulk planners Ghana"],
  calendars: ["calendars Ghana", "desk calendars Accra", "buy calendar online Ghana", "wall calendar Ghana", "office calendar Accra", "2027 calendar Ghana", "calendar supplier Ghana", "corporate calendars Accra", "calendar delivery Ghana", "bulk calendars Ghana"],
  stickyNotes: ["adhesive memo notes Ghana", "post it notes Accra", "buy sticky notes online Ghana", "memo pads Ghana", "office sticky notes Ghana", "self adhesive notes Accra", "sticky note supplier Ghana", "colour sticky notes Accra", "sticky notes delivery Ghana", "bulk sticky notes Ghana"],
  correction: ["correction tape Ghana", "correction fluid Accra", "buy correction supplies Ghana", "erasers Ghana", "office correction supplies Accra", "school erasers Ghana", "correction pen Ghana", "correction products supplier Ghana", "correction supplies delivery Accra", "bulk correction supplies Ghana"],
  geometry: ["geometry sets Ghana", "mathematical instruments Accra", "buy geometry set online Ghana", "school rulers Ghana", "compass and protractor Ghana", "student geometry set Accra", "maths supplies Ghana", "geometry set supplier Ghana", "geometry set delivery Accra", "bulk geometry sets Ghana"],
  calculators: ["desktop calculators Ghana", "office calculator Accra", "buy calculator online Ghana", "scientific calculator Ghana", "financial calculator Accra", "school calculator Ghana", "desktop calculator supplier Ghana", "calculator delivery Accra", "bulk calculators Ghana", "best calculator for school Ghana"],
  schoolBags: ["school bags Ghana", "school backpacks Accra", "buy school bag online Ghana", "student backpacks Ghana", "school bag supplier Accra", "kids school bags Ghana", "school bag delivery Ghana", "back to school bags Ghana", "bulk school bags Accra", "school backpack price Ghana"],
  examSupplies: ["exam stationery Ghana", "BECE stationery Accra", "WASSCE stationery Ghana", "exam pencils Ghana", "exam supplies supplier Accra", "school examination supplies Ghana", "exam pads Ghana", "student exam kits Ghana", "exam stationery delivery Accra", "bulk exam supplies Ghana"],
  teacherSupplies: ["teacher supplies Ghana", "classroom teacher stationery Accra", "teacher planner Ghana", "lesson planning books Ghana", "teacher markers Accra", "school administration supplies Ghana", "teacher stationery supplier Ghana", "classroom organisation Ghana", "teacher supplies delivery Accra", "bulk teacher supplies Ghana"],
  library: ["library supplies Ghana", "school library stationery Accra", "library labels Ghana", "book covering supplies Ghana", "library organisation Ghana", "library books supplier Ghana", "library filing supplies Accra", "school reading supplies Ghana", "library supplies delivery Ghana", "bulk library supplies Ghana"],
  reading: ["reading books Ghana", "children reading books Accra", "buy story books online Ghana", "early readers Ghana", "educational reading books Ghana", "young readers books Accra", "reading materials supplier Ghana", "school reading programme supplies", "reading books delivery Accra", "bulk reading books Ghana"],
  stamps: ["rubber stamps Ghana", "office stamps Accra", "company stamp Ghana", "date stamp Accra", "self inking stamp Ghana", "custom stamp supplier Accra", "business stamps Ghana", "stamp pad Ghana", "office stamp delivery Ghana", "bulk stamps Accra"],
  labels: ["labels Ghana", "office labels Accra", "address labels Ghana", "file labels Ghana", "label stickers Accra", "shipping labels Ghana", "product labels supplier Ghana", "barcode labels Accra", "label delivery Ghana", "bulk labels Ghana"],
  binding: ["binding supplies Ghana", "book binding covers Accra", "binding combs Ghana", "binding machines Accra", "document binding supplies Ghana", "spiral binding Ghana", "binding accessories supplier Ghana", "office binding products Accra", "binding supplies delivery Ghana", "bulk binding supplies Ghana"],
  laminating: ["laminating supplies Ghana", "laminating pouches Accra", "laminator machine Ghana", "A4 laminating pouches Ghana", "document laminating Accra", "school laminating supplies Ghana", "lamination supplier Ghana", "laminating film Accra", "laminating supplies delivery Ghana", "bulk laminating pouches Ghana"],
  shredding: ["paper shredders Ghana", "office shredder Accra", "buy shredder online Ghana", "document shredder Ghana", "cross cut shredder Accra", "small office shredder Ghana", "shredder supplier Ghana", "secure document disposal Ghana", "shredder delivery Accra", "bulk office shredders Ghana"],
  whiteboards: ["office whiteboards Ghana", "whiteboard Accra", "buy whiteboard online Ghana", "magnetic whiteboard Ghana", "office whiteboard Accra", "classroom whiteboard Ghana", "whiteboard markers Ghana", "whiteboard supplier Accra", "whiteboard delivery Ghana", "bulk whiteboards Ghana"],
  presentation: ["presentation folders Ghana", "presentation boards Accra", "project presentation supplies Ghana", "training presentation supplies Accra", "display boards Ghana", "projector accessories Ghana", "presentation stationery supplier Ghana", "business presentation materials Ghana", "presentation supplies delivery Accra", "bulk presentation supplies Ghana"],
  thermal: ["thermal paper Ghana", "POS paper rolls Accra", "cash register rolls Ghana", "receipt rolls Ghana", "thermal rolls supplier Accra", "80mm thermal paper Ghana", "57mm thermal paper Ghana", "ATM paper rolls Ghana", "thermal paper delivery Ghana", "bulk POS rolls Ghana"],
  pos: ["POS supplies Ghana", "point of sale paper Accra", "POS roll supplier Ghana", "cashier stationery Ghana", "till rolls Accra", "retail shop supplies Ghana", "POS printer paper Ghana", "shop receipt rolls Accra", "POS supplies delivery Ghana", "bulk retail supplies Ghana"],
  copier: ["photocopier supplies Ghana", "copier toner Accra", "copier paper Ghana", "office copier accessories Ghana", "copy machine supplies Accra", "copier consumables Ghana", "photocopier supplier Ghana", "copy room supplies Accra", "copier supplies delivery Ghana", "bulk copier supplies Ghana"],
  printerParts: ["printer add-ons Ghana", "printer cables Accra", "printer maintenance supplies Ghana", "printer drums Ghana", "printer parts supplier Accra", "printer replacement parts Ghana", "office printer accessories Ghana", "printer tray supplies Accra", "printer accessories delivery Ghana", "bulk printer parts Ghana"],
  security: ["secure office supplies Ghana", "confidential document envelopes Ghana", "security stationery Accra", "tamper evident bags Ghana", "document security supplies Ghana", "secure filing Ghana", "confidential office stationery Accra", "secure document storage Ghana", "security supplies delivery Ghana", "bulk security stationery Ghana"],
  officeSetup: ["new office stationery checklist Ghana", "office setup supplies Accra", "startup office supplies Ghana", "office opening stationery Ghana", "small office setup Accra", "new business stationery Ghana", "office starter pack Ghana", "office setup supplier Accra", "office setup delivery Ghana", "bulk office setup Ghana"],
  backToSchool: ["back to school supplies Ghana", "back to school stationery Accra", "back to school shopping Ghana", "school list supplies Ghana", "back to school books Accra", "back to school pencils Ghana", "back to school deals Ghana", "school term supplies Accra", "back to school delivery Ghana", "bulk back to school supplies Ghana"],
  yearEnd: ["year end office supplies Ghana", "annual office stationery Accra", "office planning supplies Ghana", "new year diary supplier Ghana", "year end procurement Accra", "corporate calendar supplier Ghana", "annual office restock Ghana", "year end stationery delivery Accra", "business planning stationery Ghana", "bulk year end supplies Ghana"],
  shopping: ["online stationery shop Ghana", "online office supply store Ghana", "stationery ecommerce Accra", "buy workplace products online Ghana", "Ghana stationery online store", "office products website Ghana", "online paper shop Accra", "online school supplies Ghana", "order stationery online Accra", "best online stationery shop Ghana"],
  Osu: ["office supplies Osu", "stationery shop Osu Accra", "A4 paper Osu", "toner supplier Osu", "school supplies Osu", "office delivery Osu", "stationery delivery Osu", "notebooks Osu", "pens shop Osu", "office stationery near Osu"],
  Airport: ["office supplies Airport Accra", "stationery shop Airport area", "A4 paper Airport Accra", "toner supplier Airport", "school supplies Airport Accra", "office delivery Airport Accra", "stationery delivery Airport", "notebooks Airport Accra", "pens shop Airport area", "office stationery near Airport"],
  EastLegon: ["office supplies East Legon", "stationery shop East Legon", "A4 paper East Legon", "toner supplier East Legon", "school supplies East Legon", "office delivery East Legon", "stationery delivery East Legon", "notebooks East Legon", "pens shop East Legon", "office stationery near East Legon"],
  Cantonments: ["office supplies Cantonments", "stationery shop Cantonments Accra", "A4 paper Cantonments", "toner supplier Cantonments", "school supplies Cantonments", "office delivery Cantonments", "stationery delivery Cantonments", "notebooks Cantonments", "pens shop Cantonments", "office stationery near Cantonments"],
  Labone: ["office supplies Labone", "stationery shop Labone Accra", "A4 paper Labone", "toner supplier Labone", "school supplies Labone", "office delivery Labone", "stationery delivery Labone", "notebooks Labone", "pens shop Labone", "office stationery near Labone"],
  Adabraka: ["office supplies Adabraka", "stationery shop Adabraka Accra", "A4 paper Adabraka", "toner supplier Adabraka", "school supplies Adabraka", "office delivery Adabraka", "stationery delivery Adabraka", "notebooks Adabraka", "pens shop Adabraka", "office stationery near Adabraka"],
  Ridge: ["office supplies Ridge Accra", "stationery shop Ridge", "A4 paper Ridge Accra", "toner supplier Ridge", "school supplies Ridge", "office delivery Ridge Accra", "stationery delivery Ridge", "notebooks Ridge", "pens shop Ridge", "office stationery near Ridge"],
  Dzorwulu: ["office supplies Dzorwulu", "stationery shop Dzorwulu Accra", "A4 paper Dzorwulu", "toner supplier Dzorwulu", "school supplies Dzorwulu", "office delivery Dzorwulu", "stationery delivery Dzorwulu", "notebooks Dzorwulu", "pens shop Dzorwulu", "office stationery near Dzorwulu"],
  Spintex: ["office supplies Spintex", "stationery shop Spintex Accra", "A4 paper Spintex", "toner supplier Spintex", "school supplies Spintex", "office delivery Spintex", "stationery delivery Spintex", "notebooks Spintex", "pens shop Spintex", "office stationery near Spintex"],
  Madina: ["office supplies Madina", "stationery shop Madina Accra", "A4 paper Madina", "toner supplier Madina", "school supplies Madina", "office delivery Madina", "stationery delivery Madina", "notebooks Madina", "pens shop Madina", "office stationery near Madina"],
  Legon: ["office supplies Legon", "stationery shop Legon Accra", "A4 paper Legon", "toner supplier Legon", "school supplies Legon", "office delivery Legon", "stationery delivery Legon", "notebooks Legon", "pens shop Legon", "office stationery near Legon"],
  Kaneshie: ["office supplies Kaneshie", "stationery shop Kaneshie Accra", "A4 paper Kaneshie", "toner supplier Kaneshie", "school supplies Kaneshie", "office delivery Kaneshie", "stationery delivery Kaneshie", "notebooks Kaneshie", "pens shop Kaneshie", "office stationery near Kaneshie"],
  Achimota: ["office supplies Achimota", "stationery shop Achimota Accra", "A4 paper Achimota", "toner supplier Achimota", "school supplies Achimota", "office delivery Achimota", "stationery delivery Achimota", "notebooks Achimota", "pens shop Achimota", "office stationery near Achimota"],
  Dansoman: ["office supplies Dansoman", "stationery shop Dansoman Accra", "A4 paper Dansoman", "toner supplier Dansoman", "school supplies Dansoman", "office delivery Dansoman", "stationery delivery Dansoman", "notebooks Dansoman", "pens shop Dansoman", "office stationery near Dansoman"],
  Kanda: ["office supplies Kanda Accra", "stationery shop Kanda", "A4 paper Kanda", "toner supplier Kanda", "school supplies Kanda", "office delivery Kanda", "stationery delivery Kanda", "notebooks Kanda", "pens shop Kanda", "office stationery near Kanda"],
  AsylumDown: ["office supplies Asylum Down", "stationery shop Asylum Down", "A4 paper Asylum Down", "toner supplier Asylum Down", "school supplies Asylum Down", "office delivery Asylum Down", "stationery delivery Asylum Down", "notebooks Asylum Down", "pens shop Asylum Down", "office stationery near Asylum Down"],
  TemaCommunities: ["office supplies Tema Community 1", "stationery shop Tema Community 2", "A4 paper Tema Community 25", "toner supplier Tema Community 8", "school supplies Tema New Town", "office delivery Tema Community 12", "stationery delivery Tema Harbour", "notebooks Tema", "pens shop Tema", "office stationery near Tema"],
  HoKumasi: ["office supplies Kumasi Ghana", "stationery shop Kumasi", "A4 paper Kumasi", "toner supplier Kumasi", "school supplies Kumasi", "office delivery Kumasi", "stationery delivery Kumasi", "notebooks Kumasi", "pens shop Kumasi", "office stationery near Kumasi"],
  TakoradiCapeCoast: ["office supplies Takoradi", "stationery shop Cape Coast", "A4 paper Takoradi", "toner supplier Cape Coast", "school supplies Takoradi", "office delivery Cape Coast", "stationery delivery Takoradi", "notebooks Cape Coast", "pens shop Takoradi", "office stationery Western Region Ghana"],
} as const;

export const GHANA_SEO_KEYWORDS = Object.values(GHANA_KEYWORD_CLUSTERS).flat();
export const TOP_GHANA_KEYWORDS = [
  ...GHANA_KEYWORD_CLUSTERS.office.slice(0, 4),
  ...GHANA_KEYWORD_CLUSTERS.a4Paper.slice(0, 3),
  ...GHANA_KEYWORD_CLUSTERS.toner.slice(0, 3),
  ...GHANA_KEYWORD_CLUSTERS.procurement.slice(0, 3),
  ...GHANA_KEYWORD_CLUSTERS.accraDelivery.slice(0, 3),
];

const CATEGORY_CLUSTERS: Record<string, keyof typeof GHANA_KEYWORD_CLUSTERS> = {
  paper: "a4Paper", "paper-printing": "a4Paper", printing: "printing", "office-equipment": "equipment", technology: "computer",
  writing: "writing", "writing-marking": "writing", filing: "filing", "filing-organisation": "filing", "desk-essentials": "desk", "desk-accessories": "desk",
  "school-supplies": "school", "arts-crafts": "art", "books-notebooks": "notebooks", books: "books", workplace: "corporate", "general-supplies": "office",
};

export function keywordsForCategory(slug: string, name: string) {
  const cluster = GHANA_KEYWORD_CLUSTERS[CATEGORY_CLUSTERS[slug] ?? "office"];
  return [...cluster, `${name} Ghana`, `${name} Accra`, `${name} supplier Ghana`];
}

export function keywordsForProduct(input: { name: string; brandName: string; categoryName?: string; specLine?: string }) {
  const category = input.categoryName?.toLowerCase() ?? "";
  const cluster = category.includes("paper") ? GHANA_KEYWORD_CLUSTERS.a4Paper : category.includes("toner") || category.includes("print") ? GHANA_KEYWORD_CLUSTERS.toner : GHANA_KEYWORD_CLUSTERS.office;
  return [...cluster.slice(0, 6), input.name, input.brandName, input.categoryName ?? "office supplies", input.specLine ?? "", `${input.name} Ghana`, `buy ${input.name} online Ghana`].filter(Boolean);
}
