import type { Metadata } from "next";
import { AdminError, AdminField, adminFieldClass } from "@/components/admin/field";
import { SubmitProgressButton } from "@/components/admin/submit-progress-button";
import { paperButton } from "@/components/commerce/paper-button";
import { listAdminNavigation } from "@/features/content/admin";
import { canAccessAdmin } from "@/lib/staff/rbac";
import { requireStaffArea } from "@/lib/staff/require";
export const metadata: Metadata = { title: "Navigation" };
export default async function AdminNavigationPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) { const actor = await requireStaffArea("navigation", "read"); const rows = await listAdminNavigation(actor.role); const canWrite = canAccessAdmin(actor.role, "navigation", "write"); const { error } = await searchParams; const form = (row?: typeof rows[number]) => <form action="/admin/navigation/mutate" method="post" className="grid gap-3 rounded-xl border border-border bg-card p-5 sm:grid-cols-[1fr_1.5fr_8rem_8rem_auto]"><input type="hidden" name="id" value={row?.id ?? ""} /><AdminField label="Label"><input name="label" required defaultValue={row?.label} className={adminFieldClass} /></AdminField><AdminField label="Link"><input name="href" required defaultValue={row?.href} placeholder="/shop" className={adminFieldClass} /></AdminField><AdminField label="Placement"><select name="placement" defaultValue={row?.placement ?? "header"} className={adminFieldClass}><option value="header">Header</option><option value="footer">Footer</option><option value="mobile">Mobile</option></select></AdminField><AdminField label="Position"><input name="position" type="number" min="0" defaultValue={row?.position ?? 0} className={adminFieldClass} /></AdminField><AdminField label="Active"><select name="active" defaultValue={row?.active === false ? "false" : "true"} className={adminFieldClass}><option value="true">Yes</option><option value="false">No</option></select></AdminField>{canWrite ? <SubmitProgressButton idleLabel={row ? "Save link" : "Create link"} pendingLabel={row ? "Saving link…" : "Creating link…"} className={`${paperButton()} sm:col-span-5 sm:justify-self-start`} /> : null}</form>; return <main><p className="text-sm uppercase tracking-[0.16em] text-slate">Website</p><h1 className="mt-2 font-heading text-3xl text-ink">Navigation</h1><p className="mt-3 text-slate">Manage links across the header, footer, and mobile navigation.</p><AdminError error={error} /><div className="mt-8 space-y-5">{rows.map((row) => <section key={row.id}>{form(row)}</section>)}{canWrite ? <section><h2 className="mb-2 font-heading text-xl text-ink">New navigation item</h2>{form()}</section> : null}</div></main>; }
