import type { Metadata } from "next";
import { listAdminPayments } from "@/features/admin/queries";
import { AdminStatusBadge } from "@/components/admin/status-badge";
import { formatGhs } from "@/lib/money";
import { requireStaffArea } from "@/lib/staff/require";

export const metadata: Metadata = { title: "Payments" };

export default async function AdminPaymentsPage({ searchParams }: { searchParams: Promise<{ status?: string; provider?: string }> }) {
  const actor = await requireStaffArea("payments", "read");
  const rows = await listAdminPayments(actor.role);
  const filters = await searchParams;
  const filteredRows = rows.filter((row) => (!filters.status || row.status === filters.status) && (!filters.provider || row.provider === filters.provider));
  return <main><p className="text-sm tracking-[0.16em] text-slate uppercase">Operations</p><h1 className="mt-2 font-heading text-3xl text-ink">Payments</h1><p className="mt-3 text-slate">Provider status and references only; raw Paystack payloads remain server-only.</p><form method="get" className="mt-6 flex flex-wrap items-end gap-3 rounded-md border border-border bg-white p-4"><label className="grid gap-1 text-xs font-medium text-slate">Status<select name="status" defaultValue={filters.status ?? ""} className="h-9 rounded-md border border-border bg-cream px-2 text-sm text-ink"><option value="">All statuses</option>{["initialized","pending","success","failed","abandoned"].map((status) => <option key={status} value={status}>{status}</option>)}</select></label><label className="grid gap-1 text-xs font-medium text-slate">Provider<select name="provider" defaultValue={filters.provider ?? ""} className="h-9 rounded-md border border-border bg-cream px-2 text-sm text-ink"><option value="">All providers</option>{["paystack","bank_transfer","purchase_order","invoice_terms"].map((provider) => <option key={provider} value={provider}>{provider.replaceAll("_", " ")}</option>)}</select></label><button type="submit" className="h-9 rounded-md bg-primary px-4 text-xs font-semibold text-primary-foreground">Apply filters</button></form>{filteredRows.length === 0 ? <p className="mt-8 text-slate">No payments match these filters.</p> : <div className="mt-8 overflow-x-auto rounded-md border border-border bg-white"><table className="w-full text-sm"><caption className="sr-only">Payments</caption><thead><tr className="border-b border-border text-left text-slate"><th className="px-4 py-3 font-medium">Order</th><th className="px-4 py-3 font-medium">Provider</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 font-medium">Amount</th><th className="px-4 py-3 font-medium">Reference</th><th className="px-4 py-3 font-medium">Received</th></tr></thead><tbody>{filteredRows.map((row) => <tr key={row.id} className="border-b border-border last:border-0"><td className="px-4 py-3">{row.orderNumber}</td><td className="px-4 py-3 capitalize">{row.provider.replaceAll("_", " ")}</td><td className="px-4 py-3"><AdminStatusBadge status={row.status} /></td><td className="px-4 py-3 tabular-nums">{formatGhs(row.amount)}</td><td className="px-4 py-3 font-mono text-xs">{row.reference ?? "—"}</td><td className="px-4 py-3 text-slate">{row.createdAt.toLocaleDateString("en-GH")}</td></tr>)}</tbody></table></div>}</main>;
}
