import type { Metadata } from "next";
import Link from "next/link";
import { absoluteUrl, pageMetadata, SITE_URL } from "@/lib/seo";

export const metadata: Metadata = pageMetadata({ title: "Delivery across Accra, Tema and Ghana", description: "PaperSource delivery across Accra and Tema, with nationwide stationery supply arranged on request.", path: "/delivery" });

export default function DeliveryPage() {
  return <main className="mx-auto max-w-3xl px-4 py-14 sm:px-6 md:py-20 lg:px-8"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "Service", "@id": `${absoluteUrl("/delivery")}#delivery-service`, name: "PaperSource Ghana delivery", description: "Direct delivery across Accra and Tema, with nationwide supply arranged on request.", url: absoluteUrl("/delivery"), provider: { "@id": `${SITE_URL}/#local-business` }, areaServed: [{ "@type": "City", name: "Accra" }, { "@type": "City", name: "Tema" }, { "@type": "Country", name: "Ghana" }], serviceType: "Workplace supplies delivery", availableChannel: { "@type": "ServiceChannel", serviceUrl: absoluteUrl("/shop"), servicePhone: "+233555001313" } }) }} /><p className="text-sm tracking-[0.16em] text-slate uppercase">Delivery</p><h1 className="mt-4 text-4xl text-ink md:text-5xl">Reliable delivery for the way you work.</h1><p className="mt-5 text-lg text-slate">PaperSource provides direct delivery across Accra and Tema. Orders outside these areas are supported through nationwide delivery arranged on request.</p><div className="mt-10 grid gap-4 sm:grid-cols-2"><section className="rounded-lg border border-border bg-card p-6"><h2 className="text-xl text-ink">Accra &amp; Tema</h2><p className="mt-3 text-sm leading-relaxed text-slate">Delivery fees and available delivery windows are calculated from the selected delivery zone at checkout.</p></section><section className="rounded-lg border border-border bg-card p-6"><h2 className="text-xl text-ink">Nationwide</h2><p className="mt-3 text-sm leading-relaxed text-slate">We will contact you to confirm the best delivery option and cost before charging a delivery fee.</p></section></div><section className="mt-10 border-t border-border pt-8"><h2 className="text-2xl text-ink">Collection and contact</h2><p className="mt-3 text-slate">Our physical locations are in Kanda and Asylum Down. For delivery questions, call <a href="tel:+233555001313" className="text-ink underline">0555 001 313</a> or <a href="tel:+233552767156" className="text-ink underline">0552 767 156</a>.</p><Link href="/shop" className="mt-6 inline-flex min-h-11 items-center rounded-md bg-ink px-5 py-2.5 text-sm font-medium text-white hover:bg-ink/90">Shop products</Link></section></main>;
}
