import type { Metadata } from "next";
import { AdminError, AdminField, adminAreaClass, adminFieldClass } from "@/components/admin/field";
import { SubmitProgressButton } from "@/components/admin/submit-progress-button";
import { paperButton } from "@/components/commerce/paper-button";
import { listAdminFaqs } from "@/features/content/admin";
import { canAccessAdmin } from "@/lib/staff/rbac";
import { requireStaffArea } from "@/lib/staff/require";
export const metadata: Metadata = { title: "FAQs" };
export default async function AdminFaqsPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) { const actor = await requireStaffArea("faqs", "read"); const rows = await listAdminFaqs(actor.role); const canWrite = canAccessAdmin(actor.role, "faqs", "write"); const { error } = await searchParams; const form = (row?: typeof rows[number]) => <form action="/admin/faqs/mutate" method="post" className="grid gap-3 rounded-xl border border-border bg-card p-5 sm:grid-cols-[1fr_8rem_8rem_auto]"><input type="hidden" name="id" value={row?.id ?? ""} /><AdminField label="Question"><input name="question" required defaultValue={row?.question} className={adminFieldClass} /></AdminField><AdminField label="Position"><input name="position" type="number" min="0" defaultValue={row?.position ?? 0} className={adminFieldClass} /></AdminField><AdminField label="Status"><select name="status" defaultValue={row?.status ?? "draft"} className={adminFieldClass}><option value="draft">Draft</option><option value="published">Published</option></select></AdminField><div className="sm:col-span-4"><AdminField label="Answer"><textarea name="answer" required defaultValue={row?.answer} rows={4} className={adminAreaClass} /></AdminField></div>{canWrite ? <SubmitProgressButton idleLabel={row ? "Save FAQ" : "Create FAQ"} pendingLabel={row ? "Saving FAQ…" : "Creating FAQ…"} className={`${paperButton()} sm:col-span-4 sm:justify-self-start`} /> : null}</form>; return <main><p className="text-sm uppercase tracking-[0.16em] text-slate">Website</p><h1 className="mt-2 font-heading text-3xl text-ink">FAQs</h1><p className="mt-3 text-slate">Publish clear answers for customers. Position controls display order.</p><AdminError error={error} /><div className="mt-8 space-y-5">{rows.map((row) => <section key={row.id}>{form(row)}</section>)}{canWrite ? <section><h2 className="mb-2 font-heading text-xl text-ink">New FAQ</h2>{form()}</section> : null}</div></main>; }
